module.exports = {
    LOG_ERROR:      'tetris:error',
    LOGINFO:        'tetris:log',
    CONNECTION:     'connection',
    DISCONNECT:     'disconnect',
    USERS_UPDATE:   'USERS_UPDATE',
    ROOMS_UPDATE:   'ROOMS_UPDATE',
    CREATE_ROOM:    'CREATE_ROOM',
    PLAYER_STATUS:  'PLAYER_STATUS',
    ACTUAL_ROOM:    'ACTUAL_ROOM',
    NEW:            'NEW',
    PLAYING:        'PLAYING',
    PAUSE:          'PAUSE',
    START:          'START',
    DROP:           'DROP',
    STAGE_WIDTH:    12,
    MULTI:          'MULTI',
    ENEMI:          'ENEMI',
    MORE_SHAPES:    'MORE_SHAPES',
    WAITING:        'WAITING',
    WINNER:         'WINNER',
    QUICK_PLAY:     'QUICK_PLAY',
    LEAVE_ENDURO:   'LEAVE_ENDURO',
    START_QUICK:    'START_QUICK'
}